namespace QLBH_VANPHONGPHAM_JD
{
    partial class FormTrangChu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormTrangChu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel1 = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.btnTaiKhoan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.btnDangXuat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTroGiup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBaoCao = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBanHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXuatHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNhapHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThongTin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.labelUser = new System.Windows.Forms.Label();
            this.nhanVienBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.qLBHTABLEBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.qLBH_TABLE = new QLBH_VANPHONGPHAM_JD.QLBH_TABLE();
            this.nhanVienTableAdapter = new QLBH_VANPHONGPHAM_JD.QLBH_TABLETableAdapters.NhanVienTableAdapter();
            this.panelBody = new System.Windows.Forms.Panel();
            this.bunifuGradientPanel1.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nhanVienBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qLBHTABLEBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qLBH_TABLE)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.Controls.Add(this.btnTaiKhoan);
            this.bunifuGradientPanel1.Controls.Add(this.panel3);
            this.bunifuGradientPanel1.Controls.Add(this.panel2);
            this.bunifuGradientPanel1.Controls.Add(this.btnDangXuat);
            this.bunifuGradientPanel1.Controls.Add(this.btnTroGiup);
            this.bunifuGradientPanel1.Controls.Add(this.btnBaoCao);
            this.bunifuGradientPanel1.Controls.Add(this.btnBanHang);
            this.bunifuGradientPanel1.Controls.Add(this.btnXuatHang);
            this.bunifuGradientPanel1.Controls.Add(this.btnNhapHang);
            this.bunifuGradientPanel1.Controls.Add(this.btnThongTin);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuGradientPanel1.Controls.Add(this.panel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.CornflowerBlue;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.CornflowerBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.CornflowerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.LightSkyBlue;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(256, 982);
            this.bunifuGradientPanel1.TabIndex = 2;
            // 
            // btnTaiKhoan
            // 
            this.btnTaiKhoan.AllowAnimations = true;
            this.btnTaiKhoan.AllowMouseEffects = true;
            this.btnTaiKhoan.AllowToggling = false;
            this.btnTaiKhoan.AnimationSpeed = 200;
            this.btnTaiKhoan.AutoGenerateColors = false;
            this.btnTaiKhoan.AutoRoundBorders = false;
            this.btnTaiKhoan.AutoSizeLeftIcon = true;
            this.btnTaiKhoan.AutoSizeRightIcon = true;
            this.btnTaiKhoan.BackColor = System.Drawing.Color.Transparent;
            this.btnTaiKhoan.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnTaiKhoan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTaiKhoan.BackgroundImage")));
            this.btnTaiKhoan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaiKhoan.ButtonText = "TÀI KHOẢN";
            this.btnTaiKhoan.ButtonTextMarginLeft = 0;
            this.btnTaiKhoan.ColorContrastOnClick = 45;
            this.btnTaiKhoan.ColorContrastOnHover = 45;
            this.btnTaiKhoan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnTaiKhoan.CustomizableEdges = borderEdges1;
            this.btnTaiKhoan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTaiKhoan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTaiKhoan.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTaiKhoan.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTaiKhoan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTaiKhoan.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnTaiKhoan.ForeColor = System.Drawing.Color.White;
            this.btnTaiKhoan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaiKhoan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaiKhoan.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTaiKhoan.IconMarginLeft = 11;
            this.btnTaiKhoan.IconPadding = 10;
            this.btnTaiKhoan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTaiKhoan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaiKhoan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTaiKhoan.IconSize = 25;
            this.btnTaiKhoan.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnTaiKhoan.IdleBorderRadius = 1;
            this.btnTaiKhoan.IdleBorderThickness = 1;
            this.btnTaiKhoan.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnTaiKhoan.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTaiKhoan.IdleIconLeftImage")));
            this.btnTaiKhoan.IdleIconRightImage = null;
            this.btnTaiKhoan.IndicateFocus = false;
            this.btnTaiKhoan.Location = new System.Drawing.Point(0, 283);
            this.btnTaiKhoan.Name = "btnTaiKhoan";
            this.btnTaiKhoan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTaiKhoan.OnDisabledState.BorderRadius = 1;
            this.btnTaiKhoan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaiKhoan.OnDisabledState.BorderThickness = 1;
            this.btnTaiKhoan.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTaiKhoan.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTaiKhoan.OnDisabledState.IconLeftImage = null;
            this.btnTaiKhoan.OnDisabledState.IconRightImage = null;
            this.btnTaiKhoan.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnTaiKhoan.onHoverState.BorderRadius = 1;
            this.btnTaiKhoan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaiKhoan.onHoverState.BorderThickness = 1;
            this.btnTaiKhoan.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnTaiKhoan.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTaiKhoan.onHoverState.IconLeftImage = null;
            this.btnTaiKhoan.onHoverState.IconRightImage = null;
            this.btnTaiKhoan.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnTaiKhoan.OnIdleState.BorderRadius = 1;
            this.btnTaiKhoan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaiKhoan.OnIdleState.BorderThickness = 1;
            this.btnTaiKhoan.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnTaiKhoan.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTaiKhoan.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTaiKhoan.OnIdleState.IconLeftImage")));
            this.btnTaiKhoan.OnIdleState.IconRightImage = null;
            this.btnTaiKhoan.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnTaiKhoan.OnPressedState.BorderRadius = 1;
            this.btnTaiKhoan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaiKhoan.OnPressedState.BorderThickness = 1;
            this.btnTaiKhoan.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnTaiKhoan.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTaiKhoan.OnPressedState.IconLeftImage = null;
            this.btnTaiKhoan.OnPressedState.IconRightImage = null;
            this.btnTaiKhoan.Size = new System.Drawing.Size(256, 63);
            this.btnTaiKhoan.TabIndex = 9;
            this.btnTaiKhoan.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTaiKhoan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTaiKhoan.TextMarginLeft = 0;
            this.btnTaiKhoan.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTaiKhoan.UseDefaultRadiusAndThickness = true;
            this.btnTaiKhoan.Click += new System.EventHandler(this.btnTaiKhoan_Click);
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.CornflowerBlue;
            this.panel3.Location = new System.Drawing.Point(0, 780);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(256, 104);
            this.panel3.TabIndex = 8;
            // 
            // panel2
            // 
            this.panel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel2.BackgroundImage")));
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(0, 882);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(256, 100);
            this.panel2.TabIndex = 7;
            // 
            // btnDangXuat
            // 
            this.btnDangXuat.AllowAnimations = true;
            this.btnDangXuat.AllowMouseEffects = true;
            this.btnDangXuat.AllowToggling = false;
            this.btnDangXuat.AnimationSpeed = 200;
            this.btnDangXuat.AutoGenerateColors = false;
            this.btnDangXuat.AutoRoundBorders = false;
            this.btnDangXuat.AutoSizeLeftIcon = true;
            this.btnDangXuat.AutoSizeRightIcon = true;
            this.btnDangXuat.BackColor = System.Drawing.Color.Transparent;
            this.btnDangXuat.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnDangXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.BackgroundImage")));
            this.btnDangXuat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.ButtonText = "ĐĂNG XUẤT";
            this.btnDangXuat.ButtonTextMarginLeft = 0;
            this.btnDangXuat.ColorContrastOnClick = 45;
            this.btnDangXuat.ColorContrastOnHover = 45;
            this.btnDangXuat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDangXuat.CustomizableEdges = borderEdges2;
            this.btnDangXuat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDangXuat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDangXuat.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnDangXuat.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDangXuat.IconMarginLeft = 11;
            this.btnDangXuat.IconPadding = 10;
            this.btnDangXuat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDangXuat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDangXuat.IconSize = 25;
            this.btnDangXuat.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnDangXuat.IdleBorderRadius = 1;
            this.btnDangXuat.IdleBorderThickness = 1;
            this.btnDangXuat.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnDangXuat.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.IdleIconLeftImage")));
            this.btnDangXuat.IdleIconRightImage = null;
            this.btnDangXuat.IndicateFocus = false;
            this.btnDangXuat.Location = new System.Drawing.Point(0, 718);
            this.btnDangXuat.Name = "btnDangXuat";
            this.btnDangXuat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.OnDisabledState.BorderRadius = 1;
            this.btnDangXuat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnDisabledState.BorderThickness = 1;
            this.btnDangXuat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.OnDisabledState.IconLeftImage = null;
            this.btnDangXuat.OnDisabledState.IconRightImage = null;
            this.btnDangXuat.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.onHoverState.BorderRadius = 1;
            this.btnDangXuat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.onHoverState.BorderThickness = 1;
            this.btnDangXuat.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.IconLeftImage = null;
            this.btnDangXuat.onHoverState.IconRightImage = null;
            this.btnDangXuat.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnDangXuat.OnIdleState.BorderRadius = 1;
            this.btnDangXuat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnIdleState.BorderThickness = 1;
            this.btnDangXuat.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnDangXuat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.OnIdleState.IconLeftImage")));
            this.btnDangXuat.OnIdleState.IconRightImage = null;
            this.btnDangXuat.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.OnPressedState.BorderRadius = 1;
            this.btnDangXuat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnPressedState.BorderThickness = 1;
            this.btnDangXuat.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.IconLeftImage = null;
            this.btnDangXuat.OnPressedState.IconRightImage = null;
            this.btnDangXuat.Size = new System.Drawing.Size(256, 63);
            this.btnDangXuat.TabIndex = 6;
            this.btnDangXuat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDangXuat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDangXuat.TextMarginLeft = 0;
            this.btnDangXuat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDangXuat.UseDefaultRadiusAndThickness = true;
            this.btnDangXuat.Click += new System.EventHandler(this.btnDangXuat_Click);
            // 
            // btnTroGiup
            // 
            this.btnTroGiup.AllowAnimations = true;
            this.btnTroGiup.AllowMouseEffects = true;
            this.btnTroGiup.AllowToggling = false;
            this.btnTroGiup.AnimationSpeed = 200;
            this.btnTroGiup.AutoGenerateColors = false;
            this.btnTroGiup.AutoRoundBorders = false;
            this.btnTroGiup.AutoSizeLeftIcon = true;
            this.btnTroGiup.AutoSizeRightIcon = true;
            this.btnTroGiup.BackColor = System.Drawing.Color.Transparent;
            this.btnTroGiup.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnTroGiup.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTroGiup.BackgroundImage")));
            this.btnTroGiup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTroGiup.ButtonText = "TRỢ GIÚP";
            this.btnTroGiup.ButtonTextMarginLeft = 0;
            this.btnTroGiup.ColorContrastOnClick = 45;
            this.btnTroGiup.ColorContrastOnHover = 45;
            this.btnTroGiup.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnTroGiup.CustomizableEdges = borderEdges3;
            this.btnTroGiup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTroGiup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTroGiup.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTroGiup.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTroGiup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTroGiup.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnTroGiup.ForeColor = System.Drawing.Color.White;
            this.btnTroGiup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTroGiup.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTroGiup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTroGiup.IconMarginLeft = 11;
            this.btnTroGiup.IconPadding = 10;
            this.btnTroGiup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTroGiup.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTroGiup.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTroGiup.IconSize = 25;
            this.btnTroGiup.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnTroGiup.IdleBorderRadius = 1;
            this.btnTroGiup.IdleBorderThickness = 1;
            this.btnTroGiup.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnTroGiup.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTroGiup.IdleIconLeftImage")));
            this.btnTroGiup.IdleIconRightImage = null;
            this.btnTroGiup.IndicateFocus = false;
            this.btnTroGiup.Location = new System.Drawing.Point(0, 656);
            this.btnTroGiup.Name = "btnTroGiup";
            this.btnTroGiup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTroGiup.OnDisabledState.BorderRadius = 1;
            this.btnTroGiup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTroGiup.OnDisabledState.BorderThickness = 1;
            this.btnTroGiup.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTroGiup.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTroGiup.OnDisabledState.IconLeftImage = null;
            this.btnTroGiup.OnDisabledState.IconRightImage = null;
            this.btnTroGiup.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnTroGiup.onHoverState.BorderRadius = 1;
            this.btnTroGiup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTroGiup.onHoverState.BorderThickness = 1;
            this.btnTroGiup.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnTroGiup.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTroGiup.onHoverState.IconLeftImage = null;
            this.btnTroGiup.onHoverState.IconRightImage = null;
            this.btnTroGiup.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnTroGiup.OnIdleState.BorderRadius = 1;
            this.btnTroGiup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTroGiup.OnIdleState.BorderThickness = 1;
            this.btnTroGiup.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnTroGiup.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTroGiup.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnTroGiup.OnIdleState.IconLeftImage")));
            this.btnTroGiup.OnIdleState.IconRightImage = null;
            this.btnTroGiup.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnTroGiup.OnPressedState.BorderRadius = 1;
            this.btnTroGiup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTroGiup.OnPressedState.BorderThickness = 1;
            this.btnTroGiup.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnTroGiup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTroGiup.OnPressedState.IconLeftImage = null;
            this.btnTroGiup.OnPressedState.IconRightImage = null;
            this.btnTroGiup.Size = new System.Drawing.Size(256, 63);
            this.btnTroGiup.TabIndex = 5;
            this.btnTroGiup.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTroGiup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTroGiup.TextMarginLeft = 0;
            this.btnTroGiup.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTroGiup.UseDefaultRadiusAndThickness = true;
            this.btnTroGiup.Click += new System.EventHandler(this.btnTroGiup_Click);
            // 
            // btnBaoCao
            // 
            this.btnBaoCao.AllowAnimations = true;
            this.btnBaoCao.AllowMouseEffects = true;
            this.btnBaoCao.AllowToggling = false;
            this.btnBaoCao.AnimationSpeed = 200;
            this.btnBaoCao.AutoGenerateColors = false;
            this.btnBaoCao.AutoRoundBorders = false;
            this.btnBaoCao.AutoSizeLeftIcon = true;
            this.btnBaoCao.AutoSizeRightIcon = true;
            this.btnBaoCao.BackColor = System.Drawing.Color.Transparent;
            this.btnBaoCao.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnBaoCao.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBaoCao.BackgroundImage")));
            this.btnBaoCao.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBaoCao.ButtonText = "BÁO CÁO";
            this.btnBaoCao.ButtonTextMarginLeft = 0;
            this.btnBaoCao.ColorContrastOnClick = 45;
            this.btnBaoCao.ColorContrastOnHover = 45;
            this.btnBaoCao.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnBaoCao.CustomizableEdges = borderEdges4;
            this.btnBaoCao.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBaoCao.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBaoCao.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBaoCao.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBaoCao.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBaoCao.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnBaoCao.ForeColor = System.Drawing.Color.White;
            this.btnBaoCao.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBaoCao.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBaoCao.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBaoCao.IconMarginLeft = 11;
            this.btnBaoCao.IconPadding = 10;
            this.btnBaoCao.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBaoCao.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBaoCao.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBaoCao.IconSize = 25;
            this.btnBaoCao.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnBaoCao.IdleBorderRadius = 1;
            this.btnBaoCao.IdleBorderThickness = 1;
            this.btnBaoCao.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnBaoCao.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnBaoCao.IdleIconLeftImage")));
            this.btnBaoCao.IdleIconRightImage = null;
            this.btnBaoCao.IndicateFocus = false;
            this.btnBaoCao.Location = new System.Drawing.Point(0, 594);
            this.btnBaoCao.Name = "btnBaoCao";
            this.btnBaoCao.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBaoCao.OnDisabledState.BorderRadius = 1;
            this.btnBaoCao.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBaoCao.OnDisabledState.BorderThickness = 1;
            this.btnBaoCao.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBaoCao.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBaoCao.OnDisabledState.IconLeftImage = null;
            this.btnBaoCao.OnDisabledState.IconRightImage = null;
            this.btnBaoCao.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnBaoCao.onHoverState.BorderRadius = 1;
            this.btnBaoCao.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBaoCao.onHoverState.BorderThickness = 1;
            this.btnBaoCao.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnBaoCao.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBaoCao.onHoverState.IconLeftImage = null;
            this.btnBaoCao.onHoverState.IconRightImage = null;
            this.btnBaoCao.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnBaoCao.OnIdleState.BorderRadius = 1;
            this.btnBaoCao.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBaoCao.OnIdleState.BorderThickness = 1;
            this.btnBaoCao.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnBaoCao.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBaoCao.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnBaoCao.OnIdleState.IconLeftImage")));
            this.btnBaoCao.OnIdleState.IconRightImage = null;
            this.btnBaoCao.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnBaoCao.OnPressedState.BorderRadius = 1;
            this.btnBaoCao.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBaoCao.OnPressedState.BorderThickness = 1;
            this.btnBaoCao.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnBaoCao.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBaoCao.OnPressedState.IconLeftImage = null;
            this.btnBaoCao.OnPressedState.IconRightImage = null;
            this.btnBaoCao.Size = new System.Drawing.Size(256, 63);
            this.btnBaoCao.TabIndex = 4;
            this.btnBaoCao.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBaoCao.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBaoCao.TextMarginLeft = 0;
            this.btnBaoCao.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBaoCao.UseDefaultRadiusAndThickness = true;
            this.btnBaoCao.Click += new System.EventHandler(this.btnBaoCao_Click);
            // 
            // btnBanHang
            // 
            this.btnBanHang.AllowAnimations = true;
            this.btnBanHang.AllowMouseEffects = true;
            this.btnBanHang.AllowToggling = false;
            this.btnBanHang.AnimationSpeed = 200;
            this.btnBanHang.AutoGenerateColors = false;
            this.btnBanHang.AutoRoundBorders = false;
            this.btnBanHang.AutoSizeLeftIcon = true;
            this.btnBanHang.AutoSizeRightIcon = true;
            this.btnBanHang.BackColor = System.Drawing.Color.Transparent;
            this.btnBanHang.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnBanHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBanHang.BackgroundImage")));
            this.btnBanHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.ButtonText = "BÁN HÀNG";
            this.btnBanHang.ButtonTextMarginLeft = 0;
            this.btnBanHang.ColorContrastOnClick = 45;
            this.btnBanHang.ColorContrastOnHover = 45;
            this.btnBanHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnBanHang.CustomizableEdges = borderEdges5;
            this.btnBanHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBanHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBanHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBanHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBanHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBanHang.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnBanHang.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBanHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBanHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBanHang.IconMarginLeft = 11;
            this.btnBanHang.IconPadding = 10;
            this.btnBanHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBanHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBanHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBanHang.IconSize = 25;
            this.btnBanHang.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnBanHang.IdleBorderRadius = 1;
            this.btnBanHang.IdleBorderThickness = 1;
            this.btnBanHang.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnBanHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnBanHang.IdleIconLeftImage")));
            this.btnBanHang.IdleIconRightImage = null;
            this.btnBanHang.IndicateFocus = false;
            this.btnBanHang.Location = new System.Drawing.Point(0, 532);
            this.btnBanHang.Name = "btnBanHang";
            this.btnBanHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBanHang.OnDisabledState.BorderRadius = 1;
            this.btnBanHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnDisabledState.BorderThickness = 1;
            this.btnBanHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBanHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBanHang.OnDisabledState.IconLeftImage = null;
            this.btnBanHang.OnDisabledState.IconRightImage = null;
            this.btnBanHang.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnBanHang.onHoverState.BorderRadius = 1;
            this.btnBanHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.onHoverState.BorderThickness = 1;
            this.btnBanHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnBanHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.onHoverState.IconLeftImage = null;
            this.btnBanHang.onHoverState.IconRightImage = null;
            this.btnBanHang.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnBanHang.OnIdleState.BorderRadius = 1;
            this.btnBanHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnIdleState.BorderThickness = 1;
            this.btnBanHang.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnBanHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnBanHang.OnIdleState.IconLeftImage")));
            this.btnBanHang.OnIdleState.IconRightImage = null;
            this.btnBanHang.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnBanHang.OnPressedState.BorderRadius = 1;
            this.btnBanHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanHang.OnPressedState.BorderThickness = 1;
            this.btnBanHang.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnBanHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBanHang.OnPressedState.IconLeftImage = null;
            this.btnBanHang.OnPressedState.IconRightImage = null;
            this.btnBanHang.Size = new System.Drawing.Size(256, 63);
            this.btnBanHang.TabIndex = 3;
            this.btnBanHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBanHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBanHang.TextMarginLeft = 0;
            this.btnBanHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBanHang.UseDefaultRadiusAndThickness = true;
            this.btnBanHang.Click += new System.EventHandler(this.btnBanHang_Click);
            // 
            // btnXuatHang
            // 
            this.btnXuatHang.AllowAnimations = true;
            this.btnXuatHang.AllowMouseEffects = true;
            this.btnXuatHang.AllowToggling = false;
            this.btnXuatHang.AnimationSpeed = 200;
            this.btnXuatHang.AutoGenerateColors = false;
            this.btnXuatHang.AutoRoundBorders = false;
            this.btnXuatHang.AutoSizeLeftIcon = true;
            this.btnXuatHang.AutoSizeRightIcon = true;
            this.btnXuatHang.BackColor = System.Drawing.Color.Transparent;
            this.btnXuatHang.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnXuatHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXuatHang.BackgroundImage")));
            this.btnXuatHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatHang.ButtonText = "XUẤT HÀNG";
            this.btnXuatHang.ButtonTextMarginLeft = 0;
            this.btnXuatHang.ColorContrastOnClick = 45;
            this.btnXuatHang.ColorContrastOnHover = 45;
            this.btnXuatHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnXuatHang.CustomizableEdges = borderEdges6;
            this.btnXuatHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXuatHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXuatHang.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnXuatHang.ForeColor = System.Drawing.Color.White;
            this.btnXuatHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXuatHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXuatHang.IconMarginLeft = 11;
            this.btnXuatHang.IconPadding = 10;
            this.btnXuatHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXuatHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXuatHang.IconSize = 25;
            this.btnXuatHang.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnXuatHang.IdleBorderRadius = 1;
            this.btnXuatHang.IdleBorderThickness = 1;
            this.btnXuatHang.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnXuatHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnXuatHang.IdleIconLeftImage")));
            this.btnXuatHang.IdleIconRightImage = null;
            this.btnXuatHang.IndicateFocus = false;
            this.btnXuatHang.Location = new System.Drawing.Point(0, 470);
            this.btnXuatHang.Name = "btnXuatHang";
            this.btnXuatHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatHang.OnDisabledState.BorderRadius = 1;
            this.btnXuatHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatHang.OnDisabledState.BorderThickness = 1;
            this.btnXuatHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatHang.OnDisabledState.IconLeftImage = null;
            this.btnXuatHang.OnDisabledState.IconRightImage = null;
            this.btnXuatHang.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnXuatHang.onHoverState.BorderRadius = 1;
            this.btnXuatHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatHang.onHoverState.BorderThickness = 1;
            this.btnXuatHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnXuatHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXuatHang.onHoverState.IconLeftImage = null;
            this.btnXuatHang.onHoverState.IconRightImage = null;
            this.btnXuatHang.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnXuatHang.OnIdleState.BorderRadius = 1;
            this.btnXuatHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatHang.OnIdleState.BorderThickness = 1;
            this.btnXuatHang.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnXuatHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXuatHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnXuatHang.OnIdleState.IconLeftImage")));
            this.btnXuatHang.OnIdleState.IconRightImage = null;
            this.btnXuatHang.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnXuatHang.OnPressedState.BorderRadius = 1;
            this.btnXuatHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatHang.OnPressedState.BorderThickness = 1;
            this.btnXuatHang.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnXuatHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXuatHang.OnPressedState.IconLeftImage = null;
            this.btnXuatHang.OnPressedState.IconRightImage = null;
            this.btnXuatHang.Size = new System.Drawing.Size(256, 63);
            this.btnXuatHang.TabIndex = 3;
            this.btnXuatHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXuatHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXuatHang.TextMarginLeft = 0;
            this.btnXuatHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXuatHang.UseDefaultRadiusAndThickness = true;
            this.btnXuatHang.Click += new System.EventHandler(this.btnXuatHang_Click);
            // 
            // btnNhapHang
            // 
            this.btnNhapHang.AllowAnimations = true;
            this.btnNhapHang.AllowMouseEffects = true;
            this.btnNhapHang.AllowToggling = false;
            this.btnNhapHang.AnimationSpeed = 200;
            this.btnNhapHang.AutoGenerateColors = false;
            this.btnNhapHang.AutoRoundBorders = false;
            this.btnNhapHang.AutoSizeLeftIcon = true;
            this.btnNhapHang.AutoSizeRightIcon = true;
            this.btnNhapHang.BackColor = System.Drawing.Color.Transparent;
            this.btnNhapHang.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnNhapHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNhapHang.BackgroundImage")));
            this.btnNhapHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.ButtonText = "NHẬP HÀNG";
            this.btnNhapHang.ButtonTextMarginLeft = 0;
            this.btnNhapHang.ColorContrastOnClick = 45;
            this.btnNhapHang.ColorContrastOnHover = 45;
            this.btnNhapHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnNhapHang.CustomizableEdges = borderEdges7;
            this.btnNhapHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNhapHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhapHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhapHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhapHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNhapHang.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnNhapHang.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNhapHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNhapHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNhapHang.IconMarginLeft = 11;
            this.btnNhapHang.IconPadding = 10;
            this.btnNhapHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNhapHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNhapHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNhapHang.IconSize = 25;
            this.btnNhapHang.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnNhapHang.IdleBorderRadius = 1;
            this.btnNhapHang.IdleBorderThickness = 1;
            this.btnNhapHang.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnNhapHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnNhapHang.IdleIconLeftImage")));
            this.btnNhapHang.IdleIconRightImage = null;
            this.btnNhapHang.IndicateFocus = false;
            this.btnNhapHang.Location = new System.Drawing.Point(0, 409);
            this.btnNhapHang.Name = "btnNhapHang";
            this.btnNhapHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNhapHang.OnDisabledState.BorderRadius = 1;
            this.btnNhapHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnDisabledState.BorderThickness = 1;
            this.btnNhapHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNhapHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNhapHang.OnDisabledState.IconLeftImage = null;
            this.btnNhapHang.OnDisabledState.IconRightImage = null;
            this.btnNhapHang.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnNhapHang.onHoverState.BorderRadius = 1;
            this.btnNhapHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.onHoverState.BorderThickness = 1;
            this.btnNhapHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnNhapHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.onHoverState.IconLeftImage = null;
            this.btnNhapHang.onHoverState.IconRightImage = null;
            this.btnNhapHang.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnNhapHang.OnIdleState.BorderRadius = 1;
            this.btnNhapHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnIdleState.BorderThickness = 1;
            this.btnNhapHang.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnNhapHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnNhapHang.OnIdleState.IconLeftImage")));
            this.btnNhapHang.OnIdleState.IconRightImage = null;
            this.btnNhapHang.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnNhapHang.OnPressedState.BorderRadius = 1;
            this.btnNhapHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhapHang.OnPressedState.BorderThickness = 1;
            this.btnNhapHang.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnNhapHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNhapHang.OnPressedState.IconLeftImage = null;
            this.btnNhapHang.OnPressedState.IconRightImage = null;
            this.btnNhapHang.Size = new System.Drawing.Size(256, 63);
            this.btnNhapHang.TabIndex = 3;
            this.btnNhapHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNhapHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNhapHang.TextMarginLeft = 0;
            this.btnNhapHang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNhapHang.UseDefaultRadiusAndThickness = true;
            this.btnNhapHang.Click += new System.EventHandler(this.btnNhapHang_Click);
            // 
            // btnThongTin
            // 
            this.btnThongTin.AllowAnimations = true;
            this.btnThongTin.AllowMouseEffects = true;
            this.btnThongTin.AllowToggling = false;
            this.btnThongTin.AnimationSpeed = 200;
            this.btnThongTin.AutoGenerateColors = false;
            this.btnThongTin.AutoRoundBorders = false;
            this.btnThongTin.AutoSizeLeftIcon = true;
            this.btnThongTin.AutoSizeRightIcon = true;
            this.btnThongTin.BackColor = System.Drawing.Color.Transparent;
            this.btnThongTin.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.btnThongTin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThongTin.BackgroundImage")));
            this.btnThongTin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTin.ButtonText = "THÔNG TIN";
            this.btnThongTin.ButtonTextMarginLeft = 0;
            this.btnThongTin.ColorContrastOnClick = 45;
            this.btnThongTin.ColorContrastOnHover = 45;
            this.btnThongTin.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnThongTin.CustomizableEdges = borderEdges8;
            this.btnThongTin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThongTin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongTin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongTin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongTin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThongTin.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnThongTin.ForeColor = System.Drawing.Color.White;
            this.btnThongTin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongTin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongTin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThongTin.IconMarginLeft = 11;
            this.btnThongTin.IconPadding = 10;
            this.btnThongTin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThongTin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongTin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThongTin.IconSize = 25;
            this.btnThongTin.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnThongTin.IdleBorderRadius = 1;
            this.btnThongTin.IdleBorderThickness = 1;
            this.btnThongTin.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.btnThongTin.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThongTin.IdleIconLeftImage")));
            this.btnThongTin.IdleIconRightImage = null;
            this.btnThongTin.IndicateFocus = false;
            this.btnThongTin.Location = new System.Drawing.Point(0, 346);
            this.btnThongTin.Name = "btnThongTin";
            this.btnThongTin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongTin.OnDisabledState.BorderRadius = 1;
            this.btnThongTin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTin.OnDisabledState.BorderThickness = 1;
            this.btnThongTin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongTin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongTin.OnDisabledState.IconLeftImage = null;
            this.btnThongTin.OnDisabledState.IconRightImage = null;
            this.btnThongTin.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnThongTin.onHoverState.BorderRadius = 1;
            this.btnThongTin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTin.onHoverState.BorderThickness = 1;
            this.btnThongTin.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnThongTin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThongTin.onHoverState.IconLeftImage = null;
            this.btnThongTin.onHoverState.IconRightImage = null;
            this.btnThongTin.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.btnThongTin.OnIdleState.BorderRadius = 1;
            this.btnThongTin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTin.OnIdleState.BorderThickness = 1;
            this.btnThongTin.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.btnThongTin.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThongTin.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThongTin.OnIdleState.IconLeftImage")));
            this.btnThongTin.OnIdleState.IconRightImage = null;
            this.btnThongTin.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.btnThongTin.OnPressedState.BorderRadius = 1;
            this.btnThongTin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTin.OnPressedState.BorderThickness = 1;
            this.btnThongTin.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnThongTin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThongTin.OnPressedState.IconLeftImage = null;
            this.btnThongTin.OnPressedState.IconRightImage = null;
            this.btnThongTin.Size = new System.Drawing.Size(256, 63);
            this.btnThongTin.TabIndex = 3;
            this.btnThongTin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThongTin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThongTin.TextMarginLeft = 0;
            this.btnThongTin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThongTin.UseDefaultRadiusAndThickness = true;
            this.btnThongTin.Click += new System.EventHandler(this.btnThongTin_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.CornflowerBlue;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "TRANG CHỦ";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges9;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.CornflowerBlue;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.CornflowerBlue;
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(0, 220);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.CornflowerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.CornflowerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.SystemColors.Highlight;
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.SystemColors.Highlight;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(256, 64);
            this.bunifuButton1.TabIndex = 2;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.bunifuPictureBox1);
            this.panel1.Controls.Add(this.labelUser);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(256, 214);
            this.panel1.TabIndex = 1;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 59;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(68, 21);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(119, 119);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // labelUser
            // 
            this.labelUser.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.labelUser.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.labelUser.Location = new System.Drawing.Point(0, 146);
            this.labelUser.Margin = new System.Windows.Forms.Padding(3);
            this.labelUser.Name = "labelUser";
            this.labelUser.Padding = new System.Windows.Forms.Padding(10);
            this.labelUser.Size = new System.Drawing.Size(256, 68);
            this.labelUser.TabIndex = 1;
            this.labelUser.Text = "TÊN NGƯỜI DÙNG";
            this.labelUser.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // nhanVienBindingSource
            // 
            this.nhanVienBindingSource.DataMember = "NhanVien";
            this.nhanVienBindingSource.DataSource = this.qLBHTABLEBindingSource;
            // 
            // qLBHTABLEBindingSource
            // 
            this.qLBHTABLEBindingSource.DataSource = this.qLBH_TABLE;
            this.qLBHTABLEBindingSource.Position = 0;
            // 
            // qLBH_TABLE
            // 
            this.qLBH_TABLE.DataSetName = "QLBH_TABLE";
            this.qLBH_TABLE.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // nhanVienTableAdapter
            // 
            this.nhanVienTableAdapter.ClearBeforeFill = true;
            // 
            // panelBody
            // 
            this.panelBody.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelBody.BackgroundImage")));
            this.panelBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBody.Location = new System.Drawing.Point(256, 0);
            this.panelBody.Name = "panelBody";
            this.panelBody.Size = new System.Drawing.Size(1589, 982);
            this.panelBody.TabIndex = 3;
            // 
            // FormTrangChu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1845, 982);
            this.Controls.Add(this.panelBody);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "FormTrangChu";
            this.Text = "FormTrangChu";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormTrangChu_FormClosing);
            this.Load += new System.EventHandler(this.FormTrangChu_Load);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nhanVienBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qLBHTABLEBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qLBH_TABLE)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuGradientPanel bunifuGradientPanel1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label labelUser;
        private System.Windows.Forms.BindingSource qLBHTABLEBindingSource;
        private QLBH_TABLE qLBH_TABLE;
        private System.Windows.Forms.BindingSource nhanVienBindingSource;
        private QLBH_TABLETableAdapters.NhanVienTableAdapter nhanVienTableAdapter;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThongTin;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDangXuat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTroGiup;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBaoCao;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBanHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXuatHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNhapHang;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Panel panelBody;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTaiKhoan;
    }
}

